# Generated by Django 2.1.5 on 2019-01-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0003_auto_20190127_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='display_url_video',
            field=models.CharField(default='', max_length=255),
        ),
    ]
