# Generated by Django 2.1.5 on 2019-01-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('using', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actu',
            name='change_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
