# Generated by Django 2.1.5 on 2019-01-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('using', '0002_auto_20190116_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actu',
            name='change_date',
            field=models.DateTimeField(null=True),
        ),
    ]
