# Generated by Django 2.1.5 on 2019-01-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('using', '0003_auto_20190116_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actu',
            name='change_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
