# Generated by Django 2.1.5 on 2019-01-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('using', '0004_auto_20190116_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actu',
            name='image',
            field=models.ImageField(upload_to='actus'),
        ),
    ]
