# Generated by Django 2.1.5 on 2019-01-26 23:04

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('actuapp', '0002_actu_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actu',
            name='image',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='actus'),
        ),
    ]
