# Generated by Django 2.1.5 on 2019-01-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuapp', '0003_auto_20190127_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actu',
            name='image',
            field=models.ImageField(upload_to='actus'),
        ),
    ]
