# Generated by Django 2.1.5 on 2019-01-27 17:44

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('actuapp', '0004_auto_20190127_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='actu',
            name='display_url_img',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='actu',
            name='image',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='actus'),
        ),
    ]
