# Generated by Django 2.1.5 on 2019-01-26 23:32

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0002_photo_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='photos'),
        ),
    ]
