# Generated by Django 2.1.5 on 2019-01-26 23:37

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0003_auto_20190127_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(permissions=(gdstorage.storage.GoogleDriveFilePermission(gdstorage.storage.GoogleDrivePermissionRole('reader'), gdstorage.storage.GoogleDrivePermissionType('user'), 'jblab976@gmail.com'),)), upload_to='photos'),
        ),
    ]
