# Generated by Django 2.1.5 on 2019-01-27 15:10

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0005_auto_20190127_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='photos'),
        ),
    ]
