# Generated by Django 2.1.5 on 2019-01-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0007_photo_dispaly_url_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='dispaly_url_img',
            new_name='display_url_img',
        ),
    ]
